package com.ch.dao;

import com.ch.entity.BtSysPermissions;
import com.ch.entity.BtSysPermissionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BtSysPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permissions
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    long countByExample(BtSysPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permissions
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    int deleteByExample(BtSysPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permissions
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    int insert(BtSysPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permissions
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    int insertSelective(BtSysPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permissions
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    List<BtSysPermissions> selectByExample(BtSysPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permissions
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtSysPermissions record, @Param("example") BtSysPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permissions
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    int updateByExample(@Param("record") BtSysPermissions record, @Param("example") BtSysPermissionsExample example);
}