package com.ch.dao;

import com.ch.entity.BtSysRoleMenu;
import com.ch.entity.BtSysRoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BtSysRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_menu
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    long countByExample(BtSysRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_menu
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    int deleteByExample(BtSysRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_menu
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    int insert(BtSysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_menu
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    int insertSelective(BtSysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_menu
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    List<BtSysRoleMenu> selectByExample(BtSysRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_menu
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtSysRoleMenu record, @Param("example") BtSysRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_menu
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    int updateByExample(@Param("record") BtSysRoleMenu record, @Param("example") BtSysRoleMenuExample example);
}