package com.ch.dao;

import com.ch.entity.BtSysUser;
import com.ch.entity.BtSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;


@Repository
public interface BtSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Wed Mar 13 11:39:16 CST 2019
     */
    long countByExample(BtSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Wed Mar 13 11:39:16 CST 2019
     */
    int deleteByExample(BtSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Wed Mar 13 11:39:16 CST 2019
     */
    int insert(BtSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Wed Mar 13 11:39:16 CST 2019
     */
    int insertSelective(BtSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Wed Mar 13 11:39:16 CST 2019
     */
    List<BtSysUser> selectByExample(BtSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Wed Mar 13 11:39:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtSysUser record, @Param("example") BtSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Wed Mar 13 11:39:16 CST 2019
     */
    int updateByExample(@Param("record") BtSysUser record, @Param("example") BtSysUserExample example);

    /**
     * 根据用户ID进行查询
     * @param userId
     * @return
     */
    @Select("select * from bt_sys_user where user_id = #{userId}")
    BtSysUser findByUserId(@Param("userId") String userId);
}