package com.ch.dao;

import com.ch.entity.BtViewNewsFan;
import com.ch.entity.BtViewNewsFanExample;
import com.ch.entity.BtViewNewsFanWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtViewNewsFanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_fan
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    long countByExample(BtViewNewsFanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_fan
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    int deleteByExample(BtViewNewsFanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_fan
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    int insert(BtViewNewsFanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_fan
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    int insertSelective(BtViewNewsFanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_fan
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    List<BtViewNewsFanWithBLOBs> selectByExampleWithBLOBs(BtViewNewsFanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_fan
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    List<BtViewNewsFan> selectByExample(BtViewNewsFanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_fan
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewNewsFanWithBLOBs record, @Param("example") BtViewNewsFanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_fan
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BtViewNewsFanWithBLOBs record, @Param("example") BtViewNewsFanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_fan
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    int updateByExample(@Param("record") BtViewNewsFan record, @Param("example") BtViewNewsFanExample example);
}