package com.ch.entity;

import java.util.Date;

public class BtSysMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.menu_id
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.name
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.path
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.parent_id
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.icon
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.component
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.sort
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.keep_alive
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String keepAlive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.type
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.create_time
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.update_time
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_menu.del_flag
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.menu_id
     *
     * @return the value of bt_sys_menu.menu_id
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.menu_id
     *
     * @param menuId the value for bt_sys_menu.menu_id
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.name
     *
     * @return the value of bt_sys_menu.name
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.name
     *
     * @param name the value for bt_sys_menu.name
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.path
     *
     * @return the value of bt_sys_menu.path
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.path
     *
     * @param path the value for bt_sys_menu.path
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.parent_id
     *
     * @return the value of bt_sys_menu.parent_id
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.parent_id
     *
     * @param parentId the value for bt_sys_menu.parent_id
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.icon
     *
     * @return the value of bt_sys_menu.icon
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.icon
     *
     * @param icon the value for bt_sys_menu.icon
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.component
     *
     * @return the value of bt_sys_menu.component
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.component
     *
     * @param component the value for bt_sys_menu.component
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.sort
     *
     * @return the value of bt_sys_menu.sort
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.sort
     *
     * @param sort the value for bt_sys_menu.sort
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.keep_alive
     *
     * @return the value of bt_sys_menu.keep_alive
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getKeepAlive() {
        return keepAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.keep_alive
     *
     * @param keepAlive the value for bt_sys_menu.keep_alive
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setKeepAlive(String keepAlive) {
        this.keepAlive = keepAlive == null ? null : keepAlive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.type
     *
     * @return the value of bt_sys_menu.type
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.type
     *
     * @param type the value for bt_sys_menu.type
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.create_time
     *
     * @return the value of bt_sys_menu.create_time
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.create_time
     *
     * @param createTime the value for bt_sys_menu.create_time
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.update_time
     *
     * @return the value of bt_sys_menu.update_time
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.update_time
     *
     * @param updateTime the value for bt_sys_menu.update_time
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_menu.del_flag
     *
     * @return the value of bt_sys_menu.del_flag
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_menu.del_flag
     *
     * @param delFlag the value for bt_sys_menu.del_flag
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}