package com.ch.entity;

import java.util.Date;

public class BtSysPermissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_permissions.id
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_permissions.alias
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_permissions.create_time
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_permissions.name
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_permissions.parent_id
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_permissions.id
     *
     * @return the value of bt_sys_permissions.id
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_permissions.id
     *
     * @param id the value for bt_sys_permissions.id
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_permissions.alias
     *
     * @return the value of bt_sys_permissions.alias
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_permissions.alias
     *
     * @param alias the value for bt_sys_permissions.alias
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_permissions.create_time
     *
     * @return the value of bt_sys_permissions.create_time
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_permissions.create_time
     *
     * @param createTime the value for bt_sys_permissions.create_time
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_permissions.name
     *
     * @return the value of bt_sys_permissions.name
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_permissions.name
     *
     * @param name the value for bt_sys_permissions.name
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_permissions.parent_id
     *
     * @return the value of bt_sys_permissions.parent_id
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_permissions.parent_id
     *
     * @param parentId the value for bt_sys_permissions.parent_id
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}