package com.ch.entity;

public class BtViewNewsFanWithBLOBs extends BtViewNewsFan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news_fan.new_content
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    private String newContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news_fan.title
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.new_content
     *
     * @return the value of bt_view_news_fan.new_content
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public String getNewContent() {
        return newContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.new_content
     *
     * @param newContent the value for bt_view_news_fan.new_content
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setNewContent(String newContent) {
        this.newContent = newContent == null ? null : newContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.title
     *
     * @return the value of bt_view_news_fan.title
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.title
     *
     * @param title the value for bt_view_news_fan.title
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}