package com.ch.entity;

import java.util.Date;

public class BtViewNews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news.id
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news.status
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news.new_content
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private String newContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news.title
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news.update_time
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news.status_str
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private String statusStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news.picture_url
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    private String pictureUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news.id
     *
     * @return the value of bt_view_news.id
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news.id
     *
     * @param id the value for bt_view_news.id
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news.status
     *
     * @return the value of bt_view_news.status
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news.status
     *
     * @param status the value for bt_view_news.status
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news.new_content
     *
     * @return the value of bt_view_news.new_content
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public String getNewContent() {
        return newContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news.new_content
     *
     * @param newContent the value for bt_view_news.new_content
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setNewContent(String newContent) {
        this.newContent = newContent == null ? null : newContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news.title
     *
     * @return the value of bt_view_news.title
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news.title
     *
     * @param title the value for bt_view_news.title
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news.update_time
     *
     * @return the value of bt_view_news.update_time
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news.update_time
     *
     * @param updateTime the value for bt_view_news.update_time
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news.status_str
     *
     * @return the value of bt_view_news.status_str
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public String getStatusStr() {
        return statusStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news.status_str
     *
     * @param statusStr the value for bt_view_news.status_str
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setStatusStr(String statusStr) {
        this.statusStr = statusStr == null ? null : statusStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news.picture_url
     *
     * @return the value of bt_view_news.picture_url
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news.picture_url
     *
     * @param pictureUrl the value for bt_view_news.picture_url
     *
     * @mbg.generated Tue Mar 12 16:01:01 CST 2019
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }
}