package com.ch.entity;

import java.util.Date;

public class BtViewNewsFan {

    private String id;


    private Integer status;

    private Date updateTime;


    private String statusStr;


    private String pictureUrl;

    private String newCategoryId;

    private String menuId;

    private Integer browseNumber;


    private Date createTime;
    private  String newContent;
    private  String title;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getNewContent() {
        return newContent;
    }

    public void setNewContent(String newContent) {
        this.newContent = newContent;
    }


    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.id
     *
     * @param id the value for bt_view_news_fan.id
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.status
     *
     * @return the value of bt_view_news_fan.status
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.status
     *
     * @param status the value for bt_view_news_fan.status
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.update_time
     *
     * @return the value of bt_view_news_fan.update_time
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.update_time
     *
     * @param updateTime the value for bt_view_news_fan.update_time
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.status_str
     *
     * @return the value of bt_view_news_fan.status_str
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public String getStatusStr() {
        return statusStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.status_str
     *
     * @param statusStr the value for bt_view_news_fan.status_str
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setStatusStr(String statusStr) {
        this.statusStr = statusStr == null ? null : statusStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.picture_url
     *
     * @return the value of bt_view_news_fan.picture_url
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.picture_url
     *
     * @param pictureUrl the value for bt_view_news_fan.picture_url
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.new_category_id
     *
     * @return the value of bt_view_news_fan.new_category_id
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public String getNewCategoryId() {
        return newCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.new_category_id
     *
     * @param newCategoryId the value for bt_view_news_fan.new_category_id
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setNewCategoryId(String newCategoryId) {
        this.newCategoryId = newCategoryId == null ? null : newCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.menu_id
     *
     * @return the value of bt_view_news_fan.menu_id
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.menu_id
     *
     * @param menuId the value for bt_view_news_fan.menu_id
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.browse_number
     *
     * @return the value of bt_view_news_fan.browse_number
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public Integer getBrowseNumber() {
        return browseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.browse_number
     *
     * @param browseNumber the value for bt_view_news_fan.browse_number
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setBrowseNumber(Integer browseNumber) {
        this.browseNumber = browseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_fan.create_time
     *
     * @return the value of bt_view_news_fan.create_time
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_fan.create_time
     *
     * @param createTime the value for bt_view_news_fan.create_time
     *
     * @mbg.generated Fri Mar 22 17:10:53 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}