package com.ch.entity;

import java.util.Date;

public class BtViewMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.id
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.name
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.tel
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.content
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.email
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.company
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.message_time
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    private Date messageTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.id
     *
     * @return the value of bt_view_message.id
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.id
     *
     * @param id the value for bt_view_message.id
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.name
     *
     * @return the value of bt_view_message.name
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.name
     *
     * @param name the value for bt_view_message.name
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.tel
     *
     * @return the value of bt_view_message.tel
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.tel
     *
     * @param tel the value for bt_view_message.tel
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.content
     *
     * @return the value of bt_view_message.content
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.content
     *
     * @param content the value for bt_view_message.content
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.email
     *
     * @return the value of bt_view_message.email
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.email
     *
     * @param email the value for bt_view_message.email
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.company
     *
     * @return the value of bt_view_message.company
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.company
     *
     * @param company the value for bt_view_message.company
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.message_time
     *
     * @return the value of bt_view_message.message_time
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public Date getMessageTime() {
        return messageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.message_time
     *
     * @param messageTime the value for bt_view_message.message_time
     *
     * @mbg.generated Tue Mar 12 15:34:19 CST 2019
     */
    public void setMessageTime(Date messageTime) {
        this.messageTime = messageTime;
    }
}