package com.ch.service;

import com.ch.base.ResponseResult;
import com.ch.entity.BtViewMenu;
import com.ch.entity.BtViewMenuExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BtViewMenuService {
    long countByExample(BtViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int deleteByExample(BtViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insert(BtViewMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insertSelective(BtViewMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    List<BtViewMenu> selectByExample(BtViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewMenu record, @Param("example") BtViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExample(@Param("record") BtViewMenu record, @Param("example") BtViewMenuExample example);


    /**
     * 展示菜单
     * @return
     */
    public ResponseResult findTree();

    /**
     * 删除菜单
     * @param id
     * @return
     */
    ResponseResult deleteMenu(String id);

}


