package com.ch.service;

import com.ch.base.ResponseResult;
import com.ch.entity.BtViewNews;
import com.ch.entity.BtViewNewsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BtViewNewsService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    long countByExample(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int deleteByExample(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int insert(BtViewNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int insertSelective(BtViewNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    List<BtViewNews> selectByExampleWithBLOBs(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    List<BtViewNews> selectByExample(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewNews record, @Param("example") BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BtViewNews record, @Param("example") BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int updateByExample(@Param("record") BtViewNews record, @Param("example") BtViewNewsExample example);

    public ResponseResult findViewNewsByMenuId(String menuId);


}
